#!/usr/bin/env python3
"""Bake sound effects into the firmware as raw PCM.

Decoding happens HERE, at build time, for the same reason the fonts and the
trig table are generated here: an MP3 decoder is tens of kilobytes of code plus
real CPU per frame, against a runtime with no libc, no malloc and no floating
point. The device should receive samples, not a codec.

8-BIT, and the reason is the whole budget. The mask ROM loads this image into
SRAM - there is no XIP - so every byte of audio competes with the framebuffer
band, the tile hashes and the segment pool. 16-bit would cost 67 KB for two
effects against ~121 KB free; 8-bit costs 34 KB and leaves room to grow. On a
laser and an explosion the quantisation reads as grit, which is not the wrong
texture for this game.

15625 Hz because that is what the hardware produces exactly: XTAL/10 for MCLK,
then /8 and /32. Asking for 16 kHz would need a fractional divider to land
2.3% away from a rate every divider hits on the nose (see i2s.h).

  ./tools/mksfx.py --list        what would be generated
  ./tools/mksfx.py               regenerate metal99/src/sfx_data.c
"""
import argparse, os, subprocess, sys, textwrap

RATE = 15625
SRC = os.path.expanduser("~/Projects/002-business/inlikeflynn-io/assets/audio/sfx")
OUT = os.path.join(os.path.dirname(__file__), "..", "metal99", "src", "sfx_data.c")

# name in C, source file, trim to seconds (None = whole file)
EFFECTS = [
    ("SFX_FIRE",  "blaster.mp3",      None),
    ("SFX_KILL",  "direct-hit-1.mp3", None),
]


def decode(path, limit):
    """MP3 -> mono 15625 Hz signed 8-bit, via ffmpeg."""
    cmd = ["ffmpeg", "-v", "error", "-i", path,
           "-ac", "1", "-ar", str(RATE), "-f", "s8", "-"]
    if limit:
        cmd[4:4] = ["-t", str(limit)]
    out = subprocess.run(cmd, capture_output=True, check=True).stdout
    return out


def normalise(pcm):
    """Scale to full 8-bit range.

    Source levels vary between effects, and a laser that is quieter than the
    explosion by chance rather than by choice is a mixing decision made by
    whoever exported the MP3. Normalising here means the game's own volume
    constants mean something.
    """
    vals = [b - 256 if b > 127 else b for b in pcm]
    peak = max(abs(v) for v in vals) or 1
    return [max(-127, min(127, (v * 127) // peak)) for v in vals]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--list", action="store_true")
    args = ap.parse_args()

    if args.list:
        for name, f, limit in EFFECTS:
            p = os.path.join(SRC, f)
            print(f"  {name:10s} {f:22s} {'present' if os.path.exists(p) else 'MISSING'}")
        return 0

    body, table, total = [], [], 0
    for name, fname, limit in EFFECTS:
        path = os.path.join(SRC, fname)
        if not os.path.exists(path):
            sys.exit(f"missing source: {path}")
        pcm = normalise(decode(path, limit))
        total += len(pcm)
        rows = textwrap.wrap(", ".join(f"{v:4d}" for v in pcm), 76)
        body.append(f"/* {fname} - {len(pcm)} samples, {len(pcm)/RATE:.2f} s */\n"
                    f"static const int8_t {name}_PCM[{len(pcm)}] = {{\n" +
                    "\n".join("    " + r for r in rows) + "\n};\n")
        table.append(f"    {{ {name}_PCM, {len(pcm)}u }}")
        print(f"  {name:10s} {len(pcm):6d} samples  {len(pcm)/1024:5.1f} KB  "
              f"{len(pcm)/RATE:.2f} s")

    with open(OUT, "w") as fh:
        fh.write("/* GENERATED by tools/mksfx.py - do not edit.\n"
                 " *\n"
                 f" * {RATE} Hz, mono, signed 8-bit, peak-normalised.\n"
                 " * Sources live outside this repo; see the generator for paths.\n"
                 " */\n"
                 '#include "sfx.h"\n\n')
        fh.write("\n".join(body))
        fh.write("\nconst sfx_clip SFX[] = {\n" + ",\n".join(table) + "\n};\n")
        fh.write(f"const uint32_t SFX_COUNT = {len(EFFECTS)}u;\n")

    print(f"  total {total/1024:.1f} KB -> {os.path.relpath(OUT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
