#!/usr/bin/env python3
"""Bake the ORIGINAL MP3 files into the firmware, byte for byte.

Not decoded, not resampled, not filtered, not normalised. The device decodes
them at runtime with minimp3 and plays them at their native rate.

WHY THIS, having previously baked PCM: the effects are mixed for full-range
playback and lose their character the moment they are resampled and
band-limited. Every transformation this script used to perform was a decision
made on the developer's behalf, and the sum of them did not sound like the
source.

It also costs LESS memory, which is the part that makes it obvious in
hindsight:

    decoded PCM at 31250 Hz, both effects   92.0 KB
    the original MP3s                       68.3 KB

The mask ROM loads this whole image into SRAM - there is no XIP - so both
numbers are SRAM, and the smaller one is also the better one.

  ./tools/mksfx.py --list     what would be generated
  ./tools/mksfx.py            regenerate metal99/src/sfx_data.c
"""
import argparse, os, subprocess, sys, textwrap

SRC = os.path.expanduser("~/Projects/002-business/inlikeflynn-io/assets/audio/sfx")
LOCAL = os.path.join(os.path.dirname(__file__), "sfx_src")
OUT = os.path.join(os.path.dirname(__file__), "..", "metal99", "src", "sfx_data.c")

EFFECTS = [
    ("SFX_FIRE",  "blaster.mp3"),
    ("SFX_KILL",  "direct-hit-1.mp3"),
]


def find(fname):
    for d in (SRC, LOCAL):
        p = os.path.join(d, fname)
        if os.path.exists(p):
            return p
    return None


def probe(path):
    """Rate and duration, for the header comment and a sanity check."""
    out = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries",
         "stream=sample_rate,channels:format=duration",
         "-of", "default=nw=1:nk=1", path],
        capture_output=True, text=True).stdout.split()
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--list", action="store_true")
    args = ap.parse_args()

    if args.list:
        for name, f in EFFECTS:
            p = find(f)
            print(f"  {name:10s} {f:22s} {'present' if p else 'MISSING'}")
        return 0

    body, table, total = [], [], 0
    for name, fname in EFFECTS:
        path = find(fname)
        if not path:
            sys.exit(f"missing source: {fname}")
        data = open(path, "rb").read()
        total += len(data)
        info = probe(path)
        rows = textwrap.wrap(", ".join(f"0x{b:02X}" for b in data), 74)
        body.append(
            f"/* {fname} - {len(data)} bytes, {' '.join(info)} */\n"
            f"static const uint8_t {name}_MP3[{len(data)}] = {{\n" +
            "\n".join("    " + r for r in rows) + "\n};\n")
        table.append(f"    {{ {name}_MP3, {len(data)}u }}")
        print(f"  {name:10s} {len(data):7d} bytes  {' '.join(info)}")

    with open(OUT, "w") as fh:
        fh.write("/* GENERATED by tools/mksfx.py - do not edit.\n"
                 " *\n"
                 " * The ORIGINAL MP3 files, byte for byte. Decoded on the device by\n"
                 " * minimp3 at playback time - no resampling, no filtering, no\n"
                 " * normalisation, nothing decided here on the mix engineer's behalf.\n"
                 " */\n"
                 '#include "sfx.h"\n\n')
        fh.write("\n".join(body))
        fh.write("\nconst sfx_clip SFX[] = {\n" + ",\n".join(table) + "\n};\n")
        fh.write(f"const uint32_t SFX_COUNT = {len(EFFECTS)}u;\n")

    print(f"  total {total/1024:.1f} KB -> {os.path.relpath(OUT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
